import type { MetadataRoute } from "next";

const BASE_URL = "https://portail-habitat.fr";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/artisans",
          "/artisans/*",
          "/artisan/*",
          "/blog/*",
          "/villes/*",
          "/devenir-pro",
          "/simulateur-devis",
          "/simulateur-devis/steps",
          "/contact-artisan",
          "/pricing",
          "/cgv",
          "/conditions-utilisation",
          "/mentions-legales",
          "/politique-de-confidentialite",
          "/politique-avis",
          // Pages SEO métiers — tous les slugs de 1er et 2e niveau
          "/plombier/*",
          "/electricien/*",
          "/chauffagiste/*",
          "/serrurier/*",
          "/macon/*",
          "/peintre/*",
          "/couvreur/*",
          "/menuisier/*",
          "/carreleur/*",
          "/paysagiste/*",
          "/climatisation/*",
          "/pompe-a-chaleur/*",
          "/isolation/*",
          "/fenetres/*",
          "/renovation/*",
          "/plaquiste/*",
          "/charpentier/*",
          "/facadier/*",
          "/terrassement/*",
          "/cuisiniste/*",
          "/pisciniste/*",
          "/vitrier/*",
          "/poseur-de-sol/*",
          "/etancheite/*",
          "/panneaux-solaires/*",
          "/poele-cheminee/*",
          "/salle-de-bain/*",
          "/portail-cloture/*",
          "/assainissement/*",
          "/metallier/*",
          "/demolition/*",
          "/ramoneur/*",
          "/store-pergola/*",
          "/travaux-hauteur/*",
          "/nettoyage-chantier/*",
          "/diagnostic-immobilier/*",
        ],
        disallow: [
          "/dashboard/*",
          "/admin/*",
          "/api/*",
          "/connexion",
          "/connexion-pro",
          "/connexion-admin277-admin",
          "/mot-de-passe-oublie",
          "/onboarding/*",
          "/test-banner-fix",
          "/_next/*",
        ],
      },
      {
        // Bloquer les crawlers IA sur les contenus propriétaires
        userAgent: ["GPTBot", "CCBot", "anthropic-ai", "Google-Extended"],
        disallow: ["/"],
      },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
    host: BASE_URL,
  };
}
