export const renovationPrestations = [
  {
    "slug": "renovation-complete-cuisine",
    "nom": "Rénovation complète de cuisine",
    "description": "Rénovation complète incluant démolition, électricité, plomberie, pose mobilier et finitions",
    "unite_prix": "forfait",
    "prix_marche": {"min": 8000, "max": 25000},
    "base_calcul": {"prix_moyen_unitaire": 15000, "temps_moyen_heures": 120},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Démolition existant", "impact_prix": 1500}, {"nom": "Électricité cuisine", "impact_prix": 2000}],
    "options": [{"nom": "Îlot central", "impact_prix": 3000}],
    "dependances": ["demolition", "electricite", "plomberie"]
  },
  {
    "slug": "renovation-cuisine-moderne",
    "nom": "Rénovation cuisine moderne",
    "description": "Modernisation d'une cuisine existante avec nouveaux équipements",
    "unite_prix": "forfait",
    "prix_marche": {"min": 6000, "max": 18000},
    "base_calcul": {"prix_moyen_unitaire": 12000, "temps_moyen_heures": 80},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Pose mobilier", "impact_prix": 4000}],
    "options": [{"nom": "Crédence sur mesure", "impact_prix": 800}],
    "dependances": ["menuiserie"]
  },
  {
    "slug": "pose-carrelage-sol",
    "nom": "Pose carrelage sol",
    "description": "Pose de carrelage au sol avec préparation support",
    "unite_prix": "m2",
    "prix_marche": {"min": 35, "max": 85},
    "base_calcul": {"prix_moyen_unitaire": 55, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Ragréage", "impact_prix": 15}],
    "options": [{"nom": "Carrelage grand format", "impact_prix": 20}],
    "dependances": ["preparation_sol"]
  },
  {
    "slug": "pose-parquet-flottant",
    "nom": "Pose parquet flottant",
    "description": "Installation de parquet flottant avec sous-couche",
    "unite_prix": "m2",
    "prix_marche": {"min": 25, "max": 65},
    "base_calcul": {"prix_moyen_unitaire": 42, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Sous-couche isolante", "impact_prix": 8}],
    "options": [{"nom": "Parquet chêne massif", "impact_prix": 35}],
    "dependances": ["preparation_sol"]
  },
  {
    "slug": "peinture-interieure",
    "nom": "Peinture intérieure",
    "description": "Application de peinture sur murs et plafonds intérieurs",
    "unite_prix": "m2",
    "prix_marche": {"min": 18, "max": 45},
    "base_calcul": {"prix_moyen_unitaire": 28, "temps_moyen_heures": 4},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Préparation supports", "impact_prix": 8}],
    "options": [{"nom": "Peinture haut de gamme", "impact_prix": 12}],
    "dependances": ["preparation_murs"]
  },
  {
    "slug": "installation-chauffage",
    "nom": "Installation chauffage",
    "description": "Installation système de chauffage central",
    "unite_prix": "forfait",
    "prix_marche": {"min": 3000, "max": 12000},
    "base_calcul": {"prix_moyen_unitaire": 6500, "temps_moyen_heures": 60},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Chaudière gaz", "impact_prix": 2500}],
    "options": [{"nom": "Pompe à chaleur", "impact_prix": 4000}],
    "dependances": ["plomberie", "electricite"]
  },
  {
    "slug": "isolation-combles",
    "nom": "Isolation combles",
    "description": "Isolation thermique des combles perdus ou aménagés",
    "unite_prix": "m2",
    "prix_marche": {"min": 20, "max": 60},
    "base_calcul": {"prix_moyen_unitaire": 35, "temps_moyen_heures": 4},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Pare-vapeur", "impact_prix": 8}],
    "options": [{"nom": "Isolation renforcée R=10", "impact_prix": 18}],
    "dependances": ["charpente"]
  },
  {
    "slug": "ravalement-facade",
    "nom": "Ravalement façade",
    "description": "Ravalement complet de façade avec enduit",
    "unite_prix": "m2",
    "prix_marche": {"min": 45, "max": 120},
    "base_calcul": {"prix_moyen_unitaire": 75, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Nettoyage façade", "impact_prix": 12}],
    "options": [{"nom": "Isolation par l'extérieur", "impact_prix": 80}],
    "dependances": ["echafaudage"]
  },
  {
    "slug": "renovation-complete-salle-bain",
    "nom": "Rénovation complète salle de bain",
    "description": "Rénovation complète salle de bain avec sanitaires",
    "unite_prix": "forfait",
    "prix_marche": {"min": 6000, "max": 20000},
    "base_calcul": {"prix_moyen_unitaire": 12000, "temps_moyen_heures": 100},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Démolition", "impact_prix": 1200}, {"nom": "Étanchéité", "impact_prix": 800}],
    "options": [{"nom": "Douche italienne", "impact_prix": 2000}],
    "dependances": ["plomberie", "electricite", "carrelage"]
  },
  {
    "slug": "installation-douche-italienne",
    "nom": "Installation douche italienne",
    "description": "Création douche à l'italienne avec évacuation",
    "unite_prix": "forfait",
    "prix_marche": {"min": 1800, "max": 5000},
    "base_calcul": {"prix_moyen_unitaire": 3200, "temps_moyen_heures": 25},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Création pente", "impact_prix": 600}, {"nom": "Évacuation linéaire", "impact_prix": 350}],
    "options": [{"nom": "Carrelage antidérapant", "impact_prix": 200}],
    "dependances": ["plomberie", "carrelage"]
  },
  {
    "slug": "pose-parquet-massif",
    "nom": "Pose parquet massif",
    "description": "Installation parquet massif cloué ou collé",
    "unite_prix": "m2",
    "prix_marche": {"min": 45, "max": 120},
    "base_calcul": {"prix_moyen_unitaire": 75, "temps_moyen_heures": 10},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Lambourdes", "impact_prix": 15}, {"nom": "Isolation phonique", "impact_prix": 12}],
    "options": [{"nom": "Parquet point de Hongrie", "impact_prix": 40}],
    "dependances": ["preparation_sol"]
  },
  {
    "slug": "renovation-toiture",
    "nom": "Rénovation toiture",
    "description": "Réfection complète de toiture avec couverture",
    "unite_prix": "m2",
    "prix_marche": {"min": 80, "max": 200},
    "base_calcul": {"prix_moyen_unitaire": 130, "temps_moyen_heures": 12},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Dépose ancienne couverture", "impact_prix": 25}, {"nom": "Liteaux neufs", "impact_prix": 18}],
    "options": [{"nom": "Tuiles terre cuite", "impact_prix": 35}],
    "dependances": ["charpente", "echafaudage"]
  },
  {
    "slug": "charpente-traditionnelle",
    "nom": "Charpente traditionnelle",
    "description": "Construction charpente bois traditionnelle",
    "unite_prix": "m2",
    "prix_marche": {"min": 60, "max": 150},
    "base_calcul": {"prix_moyen_unitaire": 95, "temps_moyen_heures": 15},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Traitement bois", "impact_prix": 12}, {"nom": "Assemblages traditionnels", "impact_prix": 25}],
    "options": [{"nom": "Chêne massif", "impact_prix": 50}],
    "dependances": ["maconnerie"]
  },
  {
    "slug": "installation-pompe-chaleur",
    "nom": "Installation pompe à chaleur",
    "description": "Installation PAC air/eau ou géothermique",
    "unite_prix": "forfait",
    "prix_marche": {"min": 8000, "max": 18000},
    "base_calcul": {"prix_moyen_unitaire": 12000, "temps_moyen_heures": 40},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Unité extérieure", "impact_prix": 3000}, {"nom": "Raccordements frigorifiques", "impact_prix": 800}],
    "options": [{"nom": "PAC géothermique", "impact_prix": 8000}],
    "dependances": ["electricite", "plomberie"]
  },
  {
    "slug": "renovation-electricite",
    "nom": "Rénovation électricité",
    "description": "Mise aux normes installation électrique complète",
    "unite_prix": "forfait",
    "prix_marche": {"min": 3000, "max": 8000},
    "base_calcul": {"prix_moyen_unitaire": 5000, "temps_moyen_heures": 50},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Tableau électrique", "impact_prix": 800}, {"nom": "Mise à la terre", "impact_prix": 400}],
    "options": [{"nom": "Domotique intégrée", "impact_prix": 2000}],
    "dependances": ["gros_oeuvre"]
  },
  {
    "slug": "renovation-plomberie",
    "nom": "Rénovation plomberie",
    "description": "Rénovation complète réseau plomberie",
    "unite_prix": "forfait",
    "prix_marche": {"min": 2500, "max": 6000},
    "base_calcul": {"prix_moyen_unitaire": 4000, "temps_moyen_heures": 40},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Évacuations PVC", "impact_prix": 800}, {"nom": "Arrivées PER", "impact_prix": 600}],
    "options": [{"nom": "Adoucisseur d'eau", "impact_prix": 1200}],
    "dependances": ["gros_oeuvre"]
  },
  {
    "slug": "amenagement-piscine",
    "nom": "Aménagement piscine",
    "description": "Construction piscine enterrée avec équipements",
    "unite_prix": "forfait",
    "prix_marche": {"min": 15000, "max": 50000},
    "base_calcul": {"prix_moyen_unitaire": 28000, "temps_moyen_heures": 200},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Terrassement", "impact_prix": 3000}, {"nom": "Filtration", "impact_prix": 2500}],
    "options": [{"nom": "Piscine à débordement", "impact_prix": 15000}],
    "dependances": ["terrassement", "electricite", "plomberie"]
  },
  {
    "slug": "creation-terrasse-bois",
    "nom": "Création terrasse bois",
    "description": "Construction terrasse bois sur plots ou lambourdes",
    "unite_prix": "m2",
    "prix_marche": {"min": 40, "max": 120},
    "base_calcul": {"prix_moyen_unitaire": 75, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Structure lambourdes", "impact_prix": 20}, {"nom": "Plots réglables", "impact_prix": 15}],
    "options": [{"nom": "Bois exotique", "impact_prix": 35}],
    "dependances": ["terrassement"]
  },
  {
    "slug": "pose-cloture",
    "nom": "Pose clôture",
    "description": "Installation clôture rigide ou grillage",
    "unite_prix": "ml",
    "prix_marche": {"min": 25, "max": 80},
    "base_calcul": {"prix_moyen_unitaire": 45, "temps_moyen_heures": 2},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Poteaux béton", "impact_prix": 12}, {"nom": "Scellement chimique", "impact_prix": 8}],
    "options": [{"nom": "Portail assorti", "impact_prix": 800}],
    "dependances": ["terrassement"]
  },
  {
    "slug": "installation-portail",
    "nom": "Installation portail",
    "description": "Pose portail battant ou coulissant avec motorisation",
    "unite_prix": "unite",
    "prix_marche": {"min": 800, "max": 3500},
    "base_calcul": {"prix_moyen_unitaire": 1800, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Piliers maçonnés", "impact_prix": 400}, {"nom": "Motorisation", "impact_prix": 600}],
    "options": [{"nom": "Portail sur mesure", "impact_prix": 1000}],
    "dependances": ["maconnerie", "electricite"]
  },
  {
    "slug": "pose-fenetres-pvc",
    "nom": "Pose fenêtres PVC",
    "description": "Installation fenêtres PVC double vitrage",
    "unite_prix": "unite",
    "prix_marche": {"min": 300, "max": 800},
    "base_calcul": {"prix_moyen_unitaire": 500, "temps_moyen_heures": 4},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Dépose ancienne", "impact_prix": 80}, {"nom": "Habillage tableau", "impact_prix": 60}],
    "options": [{"nom": "Triple vitrage", "impact_prix": 150}],
    "dependances": ["menuiserie"]
  },
  {
    "slug": "entretien-jardin",
    "nom": "Entretien jardin",
    "description": "Entretien complet espaces verts et jardins",
    "unite_prix": "forfait",
    "prix_marche": {"min": 200, "max": 800},
    "base_calcul": {"prix_moyen_unitaire": 400, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Tonte pelouse", "impact_prix": 80}, {"nom": "Taille haies", "impact_prix": 120}],
    "options": [{"nom": "Traitement phytosanitaire", "impact_prix": 150}],
    "dependances": ["paysagisme"]
  },
  {
    "slug": "taille-haies",
    "nom": "Taille haies",
    "description": "Taille et entretien haies et arbustes",
    "unite_prix": "ml",
    "prix_marche": {"min": 8, "max": 25},
    "base_calcul": {"prix_moyen_unitaire": 15, "temps_moyen_heures": 1},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Évacuation déchets verts", "impact_prix": 3}],
    "options": [{"nom": "Taille architecturée", "impact_prix": 8}],
    "dependances": ["paysagisme"]
  },
  {
    "slug": "tonte-pelouse",
    "nom": "Tonte pelouse",
    "description": "Tonte et entretien pelouse avec ramassage",
    "unite_prix": "m2",
    "prix_marche": {"min": 0.5, "max": 2},
    "base_calcul": {"prix_moyen_unitaire": 1, "temps_moyen_heures": 2},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Bordures", "impact_prix": 0.3}],
    "options": [{"nom": "Mulching", "impact_prix": 0.2}],
    "dependances": ["paysagisme"]
  },
  {
    "slug": "dallage-exterieur",
    "nom": "Dallage extérieur",
    "description": "Pose dallage pierre naturelle ou béton",
    "unite_prix": "m2",
    "prix_marche": {"min": 30, "max": 100},
    "base_calcul": {"prix_moyen_unitaire": 60, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Lit de sable", "impact_prix": 8}, {"nom": "Joints sable polymère", "impact_prix": 5}],
    "options": [{"nom": "Pierre naturelle", "impact_prix": 40}],
    "dependances": ["terrassement"]
  },
  {
    "slug": "maconnerie-generale",
    "nom": "Maçonnerie générale",
    "description": "Travaux de maçonnerie tous corps d'état",
    "unite_prix": "forfait",
    "prix_marche": {"min": 2000, "max": 8000},
    "base_calcul": {"prix_moyen_unitaire": 4500, "temps_moyen_heures": 60},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Fondations", "impact_prix": 1500}, {"nom": "Élévation murs", "impact_prix": 2000}],
    "options": [{"nom": "Mur en pierre", "impact_prix": 3000}],
    "dependances": ["terrassement"]
  },
  {
    "slug": "demolition",
    "nom": "Démolition",
    "description": "Démolition partielle ou complète avec évacuation",
    "unite_prix": "m3",
    "prix_marche": {"min": 40, "max": 120},
    "base_calcul": {"prix_moyen_unitaire": 75, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Évacuation gravats", "impact_prix": 25}],
    "options": [{"nom": "Tri sélectif", "impact_prix": 15}],
    "dependances": ["gros_oeuvre"]
  },
  {
    "slug": "extension-maison",
    "nom": "Extension maison",
    "description": "Construction extension tous corps d'état",
    "unite_prix": "m2",
    "prix_marche": {"min": 1200, "max": 2500},
    "base_calcul": {"prix_moyen_unitaire": 1800, "temps_moyen_heures": 100},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Gros œuvre", "impact_prix": 800}, {"nom": "Second œuvre", "impact_prix": 600}],
    "options": [{"nom": "Toit terrasse", "impact_prix": 400}],
    "dependances": ["maconnerie", "charpente", "couverture"]
  },
  {
    "slug": "amenagement-combles",
    "nom": "Aménagement combles",
    "description": "Aménagement combles perdus en espace habitable",
    "unite_prix": "m2",
    "prix_marche": {"min": 500, "max": 1200},
    "base_calcul": {"prix_moyen_unitaire": 800, "temps_moyen_heures": 20},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Plancher", "impact_prix": 200}, {"nom": "Isolation", "impact_prix": 150}],
    "options": [{"nom": "Velux", "impact_prix": 600}],
    "dependances": ["charpente", "electricite"]
  },
  {
    "slug": "pose-velux",
    "nom": "Pose Velux",
    "description": "Installation fenêtre de toit Velux avec raccords",
    "unite_prix": "unite",
    "prix_marche": {"min": 400, "max": 1000},
    "base_calcul": {"prix_moyen_unitaire": 650, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Raccords étanchéité", "impact_prix": 120}],
    "options": [{"nom": "Velux électrique", "impact_prix": 300}],
    "dependances": ["couverture", "charpente"]
  },
  {
    "slug": "installation-climatisation",
    "nom": "Installation climatisation",
    "description": "Installation système climatisation réversible",
    "unite_prix": "unite",
    "prix_marche": {"min": 800, "max": 2500},
    "base_calcul": {"prix_moyen_unitaire": 1500, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Unité extérieure", "impact_prix": 400}, {"nom": "Liaisons frigorifiques", "impact_prix": 200}],
    "options": [{"nom": "Multi-split", "impact_prix": 800}],
    "dependances": ["electricite"]
  },
  {
    "slug": "pose-gouttiere",
    "nom": "Pose gouttière",
    "description": "Installation gouttières et descentes pluviales",
    "unite_prix": "ml",
    "prix_marche": {"min": 15, "max": 45},
    "base_calcul": {"prix_moyen_unitaire": 28, "temps_moyen_heures": 2},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Crochets de fixation", "impact_prix": 5}],
    "options": [{"nom": "Gouttière cuivre", "impact_prix": 25}],
    "dependances": ["couverture"]
  },
  {
    "slug": "installation-spa",
    "nom": "Installation spa",
    "description": "Installation spa extérieur avec raccordements",
    "unite_prix": "forfait",
    "prix_marche": {"min": 8000, "max": 25000},
    "base_calcul": {"prix_moyen_unitaire": 15000, "temps_moyen_heures": 30},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Dalle béton", "impact_prix": 1500}, {"nom": "Raccordements", "impact_prix": 800}],
    "options": [{"nom": "Spa encastré", "impact_prix": 5000}],
    "dependances": ["electricite", "plomberie"]
  },
  {
    "slug": "arrosage-automatique",
    "nom": "Arrosage automatique",
    "description": "Installation système d'arrosage automatique",
    "unite_prix": "m2",
    "prix_marche": {"min": 8, "max": 25},
    "base_calcul": {"prix_moyen_unitaire": 15, "temps_moyen_heures": 4},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Programmateur", "impact_prix": 200}, {"nom": "Électrovannes", "impact_prix": 150}],
    "options": [{"nom": "Sonde météo", "impact_prix": 300}],
    "dependances": ["plomberie", "electricite"]
  },
  {
    "slug": "eclairage-exterieur",
    "nom": "Éclairage extérieur",
    "description": "Installation éclairage jardin et terrasse",
    "unite_prix": "forfait",
    "prix_marche": {"min": 500, "max": 2000},
    "base_calcul": {"prix_moyen_unitaire": 1000, "temps_moyen_heures": 12},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Câblage enterré", "impact_prix": 300}],
    "options": [{"nom": "Éclairage LED", "impact_prix": 400}],
    "dependances": ["electricite"]
  },
  {
    "slug": "pose-abri-jardin",
    "nom": "Pose abri jardin",
    "description": "Montage abri de jardin avec dalle béton",
    "unite_prix": "forfait",
    "prix_marche": {"min": 800, "max": 3000},
    "base_calcul": {"prix_moyen_unitaire": 1500, "temps_moyen_heures": 16},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Dalle béton", "impact_prix": 400}],
    "options": [{"nom": "Abri sur mesure", "impact_prix": 1000}],
    "dependances": ["terrassement"]
  },
  {
    "slug": "peinture-exterieure",
    "nom": "Peinture extérieure",
    "description": "Peinture façade et boiseries extérieures",
    "unite_prix": "m2",
    "prix_marche": {"min": 25, "max": 60},
    "base_calcul": {"prix_moyen_unitaire": 40, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Préparation supports", "impact_prix": 12}, {"nom": "Sous-couche", "impact_prix": 8}],
    "options": [{"nom": "Peinture anti-mousse", "impact_prix": 15}],
    "dependances": ["echafaudage"]
  },
  {
    "slug": "pose-sol-souple",
    "nom": "Pose sol souple",
    "description": "Installation revêtement souple PVC, lino, moquette",
    "unite_prix": "m2",
    "prix_marche": {"min": 15, "max": 45},
    "base_calcul": {"prix_moyen_unitaire": 28, "temps_moyen_heures": 4},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Ragréage", "impact_prix": 8}, {"nom": "Sous-couche", "impact_prix": 5}],
    "options": [{"nom": "Sol PVC clipsable", "impact_prix": 12}],
    "dependances": ["preparation_sol"]
  },
  {
    "slug": "pose-sol-dur",
    "nom": "Pose sol dur",
    "description": "Installation carrelage, pierre naturelle, béton ciré",
    "unite_prix": "m2",
    "prix_marche": {"min": 40, "max": 150},
    "base_calcul": {"prix_moyen_unitaire": 80, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Chape", "impact_prix": 20}, {"nom": "Primaire accrochage", "impact_prix": 12}],
    "options": [{"nom": "Pierre naturelle", "impact_prix": 60}],
    "dependances": ["preparation_sol"]
  },
  {
    "slug": "jointoyage",
    "nom": "Jointoyage",
    "description": "Réalisation joints placo, carrelage, maçonnerie",
    "unite_prix": "m2",
    "prix_marche": {"min": 8, "max": 25},
    "base_calcul": {"prix_moyen_unitaire": 15, "temps_moyen_heures": 3},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Ponçage", "impact_prix": 5}, {"nom": "Enduit lissage", "impact_prix": 8}],
    "options": [{"nom": "Joint époxy", "impact_prix": 8}],
    "dependances": ["cloisons"]
  },
  {
    "slug": "isolation-murs-interieurs",
    "nom": "Isolation murs intérieurs",
    "description": "Isolation thermique et phonique murs intérieurs",
    "unite_prix": "m2",
    "prix_marche": {"min": 25, "max": 65},
    "base_calcul": {"prix_moyen_unitaire": 42, "temps_moyen_heures": 5},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Pare-vapeur", "impact_prix": 8}, {"nom": "Ossature métallique", "impact_prix": 15}],
    "options": [{"nom": "Isolation renforcée", "impact_prix": 18}],
    "dependances": ["cloisons"]
  },
  {
    "slug": "isolation-murs-exterieurs",
    "nom": "Isolation murs extérieurs",
    "description": "ITE isolation thermique par l'extérieur",
    "unite_prix": "m2",
    "prix_marche": {"min": 80, "max": 180},
    "base_calcul": {"prix_moyen_unitaire": 120, "temps_moyen_heures": 8},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Enduit finition", "impact_prix": 25}, {"nom": "Fixations mécaniques", "impact_prix": 12}],
    "options": [{"nom": "Bardage bois", "impact_prix": 40}],
    "dependances": ["echafaudage"]
  },
  {
    "slug": "extension-beton",
    "nom": "Extension béton",
    "description": "Extension maison structure béton banché",
    "unite_prix": "m2",
    "prix_marche": {"min": 1400, "max": 2800},
    "base_calcul": {"prix_moyen_unitaire": 2000, "temps_moyen_heures": 120},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Fondations", "impact_prix": 400}, {"nom": "Ferraillage", "impact_prix": 200}],
    "options": [{"nom": "Béton architectonique", "impact_prix": 300}],
    "dependances": ["terrassement", "maconnerie"]
  },
  {
    "slug": "extension-bois",
    "nom": "Extension bois",
    "description": "Extension ossature bois avec isolation",
    "unite_prix": "m2",
    "prix_marche": {"min": 1200, "max": 2200},
    "base_calcul": {"prix_moyen_unitaire": 1600, "temps_moyen_heures": 80},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Ossature bois", "impact_prix": 300}, {"nom": "Isolation intégrée", "impact_prix": 150}],
    "options": [{"nom": "Bardage mélèze", "impact_prix": 200}],
    "dependances": ["charpente"]
  },
  {
    "slug": "surelevation",
    "nom": "Surélévation",
    "description": "Surélévation maison avec étage supplémentaire",
    "unite_prix": "m2",
    "prix_marche": {"min": 1600, "max": 3000},
    "base_calcul": {"prix_moyen_unitaire": 2200, "temps_moyen_heures": 150},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Renforcement structure", "impact_prix": 500}, {"nom": "Nouvelle charpente", "impact_prix": 400}],
    "options": [{"nom": "Toit terrasse", "impact_prix": 400}],
    "dependances": ["charpente", "maconnerie"]
  },
  {
    "slug": "pose-carrelage-mural",
    "nom": "Pose carrelage mural",
    "description": "Pose carrelage sur murs intérieurs et extérieurs",
    "unite_prix": "m2",
    "prix_marche": {"min": 30, "max": 80},
    "base_calcul": {"prix_moyen_unitaire": 50, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Préparation mur", "impact_prix": 12}, {"nom": "Colle carrelage", "impact_prix": 8}],
    "options": [{"nom": "Carrelage grand format", "impact_prix": 25}],
    "dependances": ["preparation_murs"]
  },
  {
    "slug": "peinture-plafond",
    "nom": "Peinture plafond",
    "description": "Application peinture plafonds avec finition",
    "unite_prix": "m2",
    "prix_marche": {"min": 20, "max": 50},
    "base_calcul": {"prix_moyen_unitaire": 32, "temps_moyen_heures": 5},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Rebouchage fissures", "impact_prix": 8}, {"nom": "Sous-couche", "impact_prix": 6}],
    "options": [{"nom": "Peinture anti-condensation", "impact_prix": 12}],
    "dependances": ["preparation_plafond"]
  },
  {
    "slug": "pose-cloison-placo",
    "nom": "Pose cloison placo",
    "description": "Installation cloisons plaques de plâtre",
    "unite_prix": "m2",
    "prix_marche": {"min": 25, "max": 55},
    "base_calcul": {"prix_moyen_unitaire": 38, "temps_moyen_heures": 4},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Rails métalliques", "impact_prix": 12}, {"nom": "Isolation phonique", "impact_prix": 15}],
    "options": [{"nom": "Placo hydrofuge", "impact_prix": 8}],
    "dependances": ["gros_oeuvre"]
  },
  {
    "slug": "pose-faience",
    "nom": "Pose faïence",
    "description": "Pose faïence murale salle de bain et cuisine",
    "unite_prix": "m2",
    "prix_marche": {"min": 35, "max": 85},
    "base_calcul": {"prix_moyen_unitaire": 55, "temps_moyen_heures": 7},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Étanchéité", "impact_prix": 15}, {"nom": "Baguettes finition", "impact_prix": 10}],
    "options": [{"nom": "Faïence mosaïque", "impact_prix": 20}],
    "dependances": ["preparation_murs"]
  },
  {
    "slug": "chape-beton",
    "nom": "Chape béton",
    "description": "Réalisation chape béton de finition",
    "unite_prix": "m2",
    "prix_marche": {"min": 18, "max": 45},
    "base_calcul": {"prix_moyen_unitaire": 28, "temps_moyen_heures": 3},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Treillis soudé", "impact_prix": 8}, {"nom": "Joints de dilatation", "impact_prix": 5}],
    "options": [{"nom": "Chape fluide", "impact_prix": 12}],
    "dependances": ["gros_oeuvre"]
  },
  {
    "slug": "enduit-facade",
    "nom": "Enduit façade",
    "description": "Application enduit extérieur monocouche ou traditionnel",
    "unite_prix": "m2",
    "prix_marche": {"min": 35, "max": 80},
    "base_calcul": {"prix_moyen_unitaire": 55, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Gobetis", "impact_prix": 8}, {"nom": "Corps d'enduit", "impact_prix": 15}],
    "options": [{"nom": "Enduit gratté", "impact_prix": 12}],
    "dependances": ["echafaudage"]
  },
  {
    "slug": "pose-bardage",
    "nom": "Pose bardage",
    "description": "Installation bardage bois, composite ou métallique",
    "unite_prix": "m2",
    "prix_marche": {"min": 40, "max": 120},
    "base_calcul": {"prix_moyen_unitaire": 75, "temps_moyen_heures": 6},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Ossature support", "impact_prix": 20}, {"nom": "Pare-pluie", "impact_prix": 8}],
    "options": [{"nom": "Bardage composite", "impact_prix": 35}],
    "dependances": ["echafaudage"]
  },
  {
    "slug": "terrassement",
    "nom": "Terrassement",
    "description": "Travaux de terrassement et nivellement terrain",
    "unite_prix": "m3",
    "prix_marche": {"min": 25, "max": 60},
    "base_calcul": {"prix_moyen_unitaire": 40, "temps_moyen_heures": 2},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Évacuation terre", "impact_prix": 15}, {"nom": "Compactage", "impact_prix": 8}],
    "options": [{"nom": "Géotextile", "impact_prix": 5}],
    "dependances": ["gros_oeuvre"]
  },
  {
    "slug": "dalle-beton",
    "nom": "Dalle béton",
    "description": "Coulage dalle béton armé avec finition",
    "unite_prix": "m2",
    "prix_marche": {"min": 35, "max": 80},
    "base_calcul": {"prix_moyen_unitaire": 55, "temps_moyen_heures": 4},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Ferraillage", "impact_prix": 15}, {"nom": "Coffrage", "impact_prix": 12}],
    "options": [{"nom": "Béton désactivé", "impact_prix": 20}],
    "dependances": ["terrassement"]
  },
  {
    "slug": "etancheite-toiture",
    "nom": "Étanchéité toiture",
    "description": "Étanchéité toiture terrasse membrane EPDM ou bitume",
    "unite_prix": "m2",
    "prix_marche": {"min": 45, "max": 100},
    "base_calcul": {"prix_moyen_unitaire": 70, "temps_moyen_heures": 5},
    "multiplicateurs_gamme": {"economique": 0.85, "standard": 1, "premium": 1.4},
    "multiplicateurs_etat": {"neuf": 0.9, "renovation": 1, "renovation_lourde": 1.3},
    "sous_prestations": [{"nom": "Pare-vapeur", "impact_prix": 12}, {"nom": "Isolation", "impact_prix": 25}],
    "options": [{"nom": "Membrane EPDM", "impact_prix": 15}],
    "dependances": ["couverture"]
  }
];

export const renovationSuggestions = [
  "Rénovation complète de cuisine", "Rénovation cuisine moderne", "Rénovation cuisine ouverte", "Installation plan de travail", "Pose plan de travail quartz", "Pose plan de travail granit", "Pose plan de travail bois", "Pose plan de travail stratifié", "Installation électroménager", "Pose cuisine équipée", "Rénovation crédence cuisine", "Pose carrelage mural cuisine", "Installation hotte aspirante", "Rénovation îlot central", "Installation évier cuisine", "Pose robinetterie cuisine", "Rénovation complète salle de bain", "Rénovation salle de bain moderne", "Rénovation salle d'eau", "Installation douche italienne", "Pose receveur de douche", "Installation baignoire", "Pose baignoire îlot", "Installation WC suspendu", "Pose carrelage salle de bain", "Pose faïence murale", "Installation vasque", "Pose meuble vasque", "Installation robinetterie", "Pose paroi de douche", "Installation VMC salle de bain", "Rénovation WC", "Pose carrelage sol", "Pose carrelage mural", "Pose carrelage grand format", "Pose carrelage imitation parquet", "Pose carrelage imitation pierre", "Pose carrelage extérieur", "Pose carrelage terrasse", "Pose carrelage piscine", "Rénovation joints carrelage", "Dépose ancien carrelage", "Pose mosaïque", "Pose grès cérame", "Pose parquet massif", "Pose parquet contrecollé", "Pose parquet flottant", "Pose parquet stratifié", "Pose parquet chêne", "Vitrification parquet", "Ponçage parquet", "Rénovation parquet ancien", "Pose parquet salle de bain", "Pose parquet cuisine", "Pose lames PVC", "Pose sol vinyle", "Pose moquette", "Pose linoléum", "Pose béton ciré", "Pose résine époxy", "Pose pierre naturelle", "Pose marbre", "Pose granit", "Pose ardoise", "Ragréage sol", "Chape liquide", "Peinture intérieure", "Peinture extérieure", "Peinture façade", "Peinture plafond", "Peinture murs", "Peinture boiseries", "Peinture volets", "Peinture portail", "Peinture garage", "Peinture décorative", "Enduit décoratif", "Papier peint", "Rénovation plomberie", "Installation chaudière", "Remplacement chaudière", "Installation chauffe-eau", "Réparation fuite", "Débouchage canalisation", "Installation radiateur", "Pose tuyauterie", "Installation compteur eau", "Rénovation évacuation", "Installation adoucisseur", "Pose ballon eau chaude", "Rénovation électrique", "Mise aux normes électrique", "Installation tableau électrique", "Pose prises électriques", "Installation éclairage", "Pose interrupteurs", "Installation domotique", "Pose luminaires", "Installation alarme", "Pose vidéophone", "Installation borne électrique", "Rénovation éclairage LED", "Installation chauffage", "Rénovation chauffage", "Installation pompe à chaleur", "Pose radiateurs", "Installation plancher chauffant", "Pose cheminée", "Installation poêle à bois", "Installation climatisation", "Entretien chaudière", "Ramonage cheminée", "Installation thermostat", "Calorifugeage", "Isolation thermique", "Isolation phonique", "Isolation combles", "Isolation combles perdus", "Isolation combles aménagés", "Isolation murs intérieurs", "Isolation murs extérieurs", "Isolation sous-sol", "Isolation cave", "Isolation garage", "Isolation toiture", "Isolation plancher", "Pose cloisons", "Cloison placo", "Cloison verrière", "Cloison amovible", "Abattage cloison", "Création ouverture", "Pose cloison séparative", "Doublage murs", "Pose rail placo", "Jointage placo", "Rénovation toiture", "Réfection toiture", "Pose tuiles", "Pose ardoises", "Étanchéité toiture", "Démoussage toiture", "Nettoyage toiture", "Pose gouttières", "Réparation fuite toiture", "Isolation toiture", "Pose velux", "Charpente", "Ravalement façade", "Nettoyage façade", "Crépi extérieur", "Crépi intérieur", "Enduit façade", "Peinture façade", "Isolation façade", "Réparation fissures", "Traitement humidité", "Bardage", "Parement pierre", "Rejointoiement", "Pose fenêtres", "Remplacement fenêtres", "Pose volets", "Installation porte d'entrée", "Pose portes intérieures", "Installation baie vitrée", "Pose velux", "Réparation volets", "Installation pergola", "Pose escalier", "Fabrication meuble", "Pose placards", "Aménagement jardin", "Création terrasse", "Pose terrasse bois", "Pose terrasse composite", "Aménagement piscine", "Pose clôture", "Création allée", "Pose portail", "Aménagement paysager", "Arrosage automatique", "Éclairage extérieur", "Pose abri jardin", "Maçonnerie générale", "Construction mur", "Démolition", "Fondations", "Dalle béton", "Création ouverture mur", "Reprise sous-œuvre", "Montage mur parpaing", "Pose linteau", "Réparation fissures", "Étanchéité cave", "Drainage", "Rénovation complète", "Rénovation énergétique", "Mise aux normes", "Extension maison", "Aménagement combles", "Création mezzanine", "Installation dressing", "Pose bibliothèque", "Aménagement bureau", "Rénovation cave", "Aménagement garage", "Installation spa"
];

// Suggestions les plus recherchées (affichées par défaut)
export const popularSuggestions = [
  "Rénovation complète de cuisine",
  "Rénovation complète salle de bain",
  "Peinture intérieure",
  "Pose carrelage sol",
  "Pose parquet flottant",
  "Installation chauffage",
  "Isolation combles",
  "Ravalement façade"
];

export const getFilteredSuggestions = (input: string, maxResults: number = 8): string[] => {
  if (!input || input.length < 2) return [];
  
  const lowercaseInput = input.toLowerCase();
  
  return renovationSuggestions
    .filter(suggestion => 
      suggestion.toLowerCase().includes(lowercaseInput)
    )
    .slice(0, maxResults);
};

export const getPopularSuggestions = (maxResults: number = 8): string[] => {
  return popularSuggestions.slice(0, maxResults);
};
